# Generated by Django 3.1.7 on 2022-01-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='app_brand',
        ),
        migrations.AlterModelTable(
            name='pricehistory',
            table='app_price_history',
        ),
        migrations.AlterModelTable(
            name='product',
            table='app_product',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='app_shop',
        ),
    ]
